/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Maks_Art22 (https://sketchfab.com/Maks_Art22)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/podium-2932a9062051454aa47e564a87239abe
Title: Podium
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from '../assets/podium.glb'

export const Stage= (props) => {
  const { nodes, materials } = useGLTF(scene)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface2_podium_0.geometry}
          material={materials.podium}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
    </group>
  )
}

// useGLTF.preload('/podium.glb')
