/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dayoung.ko (https://sketchfab.com/dayoung.ko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-stage-469167bc55cc427c85e272eb5c3504c4
Title: Simple Stage
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from '../assets/simple_stage.glb'

export const Stage2 = ({position, scale, ...props}) => {
  const { nodes, materials } = useGLTF(scene)
  return (
    <group {...props} dispose={null}>
      <group
        position={[46.2, 0.262, 27.853]}
        rotation={[0, 0, -Math.PI]}
        scale={[-5.351, 0.25, 5.351]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['Material.007']}
        />
      </group>
    </group>
  )
}

// useGLTF.preload('/simple_stage.glb')
