/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: InvisiblePolygon (https://sketchfab.com/InvisiblePolygon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wardrobe-with-vinatge-clothes-40d4d44217564817b6f00977901dc19f
Title: Wardrobe with vinatge clothes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from '../assets/wardrobe.glb'

const WardrobeModel = (props) => {
  const { nodes, materials } = useGLTF(scene)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wardrobe_Material001_0.geometry}
            material={materials['Material.001']}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1_hanger1_0.geometry}
            material={materials.hanger1}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1001_hanger1_0.geometry}
            material={materials.hanger1}
            position={[0, 0, 105.527]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1002_hanger1_0.geometry}
            material={materials.hanger1}
            position={[0, 0, 213.07]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1003_hanger1_0.geometry}
            material={materials.hanger1}
            position={[0, 0, 309.858]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1004_hanger1_0.geometry}
            material={materials.hanger1}
            position={[0, 0, 416.057]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1005_hanger1_0.geometry}
            material={materials.hanger1}
            position={[0, 0, 506.797]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1006_hanger1_0.geometry}
            material={materials.hanger1}
            position={[0, 0, 598.88]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1007_hanger1_0.geometry}
            material={materials.hanger1}
            position={[0, 0, 699.03]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1008_hanger1_0.geometry}
            material={materials.hanger1}
            position={[0, 0, 785.736]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1009_hanger1_0.geometry}
            material={materials.hanger1}
            position={[0, 0, 888.574]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1010_hanger1_0.geometry}
            material={materials.hanger1}
            position={[0, 0, 963.854]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1011_hanger1_0.geometry}
            material={materials.hanger1}
            position={[0, 0, 1049.889]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hanger_1012_hanger1_0.geometry}
            material={materials.hanger1}
            position={[0, 0, 1152.727]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirt4_tshirt_brown_0.geometry}
            material={materials.tshirt_brown}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirt3_tshirt_purple_0.geometry}
            material={materials.tshirt_purple}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirt7_tshirt_brown_0.geometry}
            material={materials.tshirt_brown}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirt5_tshirt_purple_0.geometry}
            material={materials.tshirt_purple}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirt8_tshirt_red_0.geometry}
            material={materials.tshirt_red}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirt1_tshirt_red_0.geometry}
            material={materials.tshirt_red}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirt12_tshirt_red_0.geometry}
            material={materials.tshirt_red}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirt11_tshirt_red_0.geometry}
            material={materials.tshirt_red}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirt10_tshirt_brown_0.geometry}
            material={materials.tshirt_brown}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirtl4_tshirtLyellow_0.geometry}
            material={materials.material_0}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirtl3_tshirtLyellow_0.geometry}
            material={materials.material_0}
            position={[0, 0, -289.671]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirtl2_shirtLblue_0.geometry}
            material={materials.shirtLblue}
            position={[0, 0, -472.569]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirtl_shirtLblue_0.geometry}
            material={materials.shirtLblue}
            position={[0, 0, -781.023]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

// useGLTF.preload('/wardrobe_with_vinatge_clothes.glb')
export default WardrobeModel;
